### ISSUE TITLE
libc.so.6: version `GLIBC_2.18' not found

### ISSUE THREAD

**Issue by huweikkk** [tinyops-ru/zabbix-lld-ws#7]
./wszl -d /usr/local/zabbix/ gen --source=file --file=urls.txt --log-level=info
./wszl: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./wszl)
my os :CentOS Linux release 7.9.200
Zabbix version: 7.0.3
is here  have  versions support  glbc 2.17 and Zabbix 7.0.3

**Comment by lebe-dev** [comment]
Thanks for report, let me check.

**Comment by huweikkk** [comment]
HI,I upgraded to GLBC version 2.18 and conducted some testing
Here is the configuration I have modified
My requirement is to monitor a domain name twice. If the domain name is not compatible or the status code is greater than 499, an alarm will be triggered
1.The trigger can be created normally, but the severity level of the trigger cannot be set. Can you tell me how to set this parameter
2.Another question is, can I force updates to the web monitoring project and trigger project content

```
cat urls.txt |grep -v "#"|grep -v "^$"
aliyun-gz-http-log-8.134.90.22|http://hs.zabbixtest.top
cat wszl.yml
zabbix:
  api:
    endpoint: http://hs.zabbixtest.top/api_jsonrpc.php
    username: Admin
    password: Y4l8sdsdssd

  trigger:
    name: "Site '${URL}' is unavailable"
    priority: 4

    # Template variables are supported: ${HOST}, ${URL}
    value: last(/${HOST}/web.test.fail[Check index page '${URL}'])<>0 or last(/${HOST}/web.test.rspcode[Check index page '${URL}',Check index page '${URL}'])>499

  scenario:
    # Search existing elements
    key-starts-with: "Check index page '"

    # Template variables are supported: ${HOST}, ${URL}
    name: "Check index page '${URL}'"
    response-timeout: "15s"
    expect-status-code: "200"
    attempts: 3
    update-interval: "5m"
```
